name: h3_ffi
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.example.com
author: long1eu <lung.razvan@gmail.com>

environment:
  sdk: '>=2.5.0-dev.2.1 <3.0.0'

dependencies:
  collection: ^1.14.0
